name: Constitution QA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check-constitution:
    name: Check constitution fields
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate constitution metadata
        run: |
          set -euo pipefail
          file=".specify/memory/constitution.md"
          if [[ ! -f "$file" ]]; then
            echo "Constitution file not found at $file" >&2
            exit 1
          fi

          # Find the version/ratified/last-amended line
          version_line=$(grep -E "^\*\*Version\*\*:" "$file" || true)
          if [[ -z "$version_line" ]]; then
            echo "Version line missing in $file" >&2
            exit 1
          fi

          # Extract version
          version=$(echo "$version_line" | sed -E 's/.*\*\*Version\*\*:[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid or missing semantic version in Version field: '$version'" >&2
            exit 1
          fi

          # Extract Ratified
          ratified=$(echo "$version_line" | sed -E 's/.*\*\*Ratified\*\*:[[:space:]]*([^| ]+).*/\1/')
          if [[ "$ratified" == TODO* ]] || [[ -z "$ratified" ]]; then
            echo "Ratification date is missing or TODO: '$ratified'" >&2
            exit 1
          fi
          if ! echo "$ratified" | grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' >/dev/null; then
            echo "Ratified date is not ISO (YYYY-MM-DD): '$ratified'" >&2
            exit 1
          fi

          # Extract Last Amended
          last=$(echo "$version_line" | sed -E 's/.*\*\*Last Amended\*\*:[[:space:]]*([^| ]+).*/\1/')
          if [[ -z "$last" ]]; then
            echo "Last Amended date missing: '$last'" >&2
            exit 1
          fi
          if ! echo "$last" | grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' >/dev/null; then
            echo "Last Amended date is not ISO (YYYY-MM-DD): '$last'" >&2
            exit 1
          fi

          echo "Constitution check passed: version=$version, ratified=$ratified, last_amended=$last"